<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_RegEmail</name>
   <tag></tag>
   <elementGuidId>78490c47-8a99-4ffd-b856-947f53073877</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RegEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1fde9ee-4b5c-4eda-836f-af604619535e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>59df1a06-9eb7-46e5-96ac-e9b2f2339461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegEmail</value>
      <webElementGuid>696d16a6-7f18-4519-9f24-2f5a173e2957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegEmail</value>
      <webElementGuid>8e27e85f-e0ce-46a9-b2cb-85d7df34e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegEmail&quot;)</value>
      <webElementGuid>ddfb3170-dbf9-47f6-8d5b-ba3a6eec8f73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegEmail']</value>
      <webElementGuid>8c157532-d5ba-4b74-b6a9-8e4fc4ca1c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div[2]/input</value>
      <webElementGuid>d4311ce4-fdf0-4e4b-9211-e53021b2bc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'RegEmail' and @name = 'RegEmail']</value>
      <webElementGuid>ceb093fc-f1dd-4b0f-a2c9-a8a36b48e3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
