<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_RegPassword</name>
   <tag></tag>
   <elementGuidId>8ea91c6d-6f77-4018-b2c6-6788589b2049</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;RegPassword&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RegPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba01b6b0-f1ad-40ed-917e-d1e1419103c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0e49db7f-0b41-43cc-86c1-b467b60817ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegPassword</value>
      <webElementGuid>62479fd7-f7c1-4a49-b0d1-2c334fabb26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegPassword</value>
      <webElementGuid>6dca30b7-5b38-475c-874d-b3157f77428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegPassword&quot;)</value>
      <webElementGuid>737573c6-af51-47c2-b8b7-20164354801e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegPassword']</value>
      <webElementGuid>8d5764bd-872c-4b36-b64b-878188834899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>a98315b8-270a-44cf-b30d-7ff0bcdb1fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'RegPassword' and @name = 'RegPassword']</value>
      <webElementGuid>f0c0a00b-99f0-42ed-a690-f97a93678cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
