<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ion-icon_Login_close-outline</name>
   <tag></tag>
   <elementGuidId>59a7d32f-0878-44bb-9ae0-d5b23efb2b5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='close-outline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;close-outline&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>131edef2-a1f0-47e4-8700-2e97bc766af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>close-outline</value>
      <webElementGuid>ac7cf56f-9bc2-4b34-8099-1c33282449ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>22a35233-91cf-4ca1-9b60-911601a9deda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>88435985-0dff-4c69-82d5-f8ad03f79b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>close outline</value>
      <webElementGuid>8d6741be-c8a6-4f73-99a2-f11a3732893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[@class=&quot;wrapper&quot;]/a[1]/span[@class=&quot;icon-close&quot;]/ion-icon[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>3e1af3b9-3e95-427e-ab38-3ad5d9ed9c0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='close-outline']</value>
      <webElementGuid>a6c736bc-a053-4272-b54b-2cf94526f7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ion-icon</value>
      <webElementGuid>26f58064-2eb0-4680-81cf-09d7f6490781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-icon[@name = 'close-outline']</value>
      <webElementGuid>b3f9803a-e0fc-4d0e-9c36-555c3f359d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
